### ISSUE TITLE
Few Tailwind classes are not coming in outpout

### ISSUE THREAD

**Issue by jagtapajittheneo** [mhsdesign/jit-browser-tailwindcss#10]
Hi;

Great work done!

I was testing this lib. and found it is skipping many tailwindcss classes in the final output.

Specially which are like  "md:w-1/4" or "w-1/2" 

Any idea?

**Comment by mhsdesign** [comment]
Moin ;)

and thanks ^^

i cannot reproduce this with v0.2.1

```js
const tailwind = createTailwindcss({
    tailwindConfig: {
        // disable normalize css
        corePlugins: { preflight: false }
    }
})

const css = await tailwind.generateStylesFromContent(`
    /* without the "@tailwind base;" */
    @tailwind components;
    @tailwind utilities;
`, ["md:w-1/4 w-1/2"]).then(console.log)
```

output:
```
    /* without the "@tailwind base;" */
    .w-1\/2 {
    width: 50%
}
    @media (min-width: 768px) {
    .md\:w-1\/4 {
        width: 25%
    }
}
```

**Comment by paweb** [comment]
Hi @mhsdesign 

I noticed the same issue and you can't reproduce it with your example because it's a problem with a browser. For example, Google Chrome transforms slash (/) and dot (.) signs into hyphen (-), and that's why it's no longer the original class name and thus doesn't work. Those are transformed into `md:w-1-4 w-1-2` which are not understandable by Tailwind CSS.
