### ISSUE TITLE
Expose `getClassOrder` from Tailwind

### ISSUE THREAD

**Issue by bkrmendy** [mhsdesign/jit-browser-tailwindcss#24]
Hi, amazing work on this library!

I'm opening this issue to provide a bit of background on #23 .

I'm working Utopia, a visual design tool that connects code to design (https://github.com/concrete-utopia/utopia/), and I'm implementing support for Tailwind projects. Since Utopia runs in the browser, to render elements that use Tailwind, I needed to find a way to generate CSS classes from Tailwind classes on the fly, in the browser. This is how I found out about https://github.com/mhsdesign/jit-browser-tailwindcss.

Another Tailwind-related feature that we want to support is to edit Tailwind classes from a Figma-like UI. For example, if an element has `... left-2 inset-x-4 ...` in its class list, we'd want to have a control that tells you what's the CSS value that `left` will generate, let you edit it, and write the new value back into the element class list. This is where class ordering comes into play. In order to figure out what value to show for the input that sets the how far the element is from the left edge of its parent, we need to figure out which class to parse to get the value for the `left` css prop (and where to write back the updated value). To do this, we need to order the class names the same way Tailwind orders them internally. 

Since your lib already solves running code from Tailwind in the browser, I piggybacked on that with #23 . I think there's an argument to be made that your lib makes it possible to run Tailwind stuff in the browser, and getting the class order from Tailwind fits that mould. If you think this is too far from the original purpose of your lib, I can go in another direction (either fork, or replicate your approach to running TW in the browser, but specialising it for my use case).

**Comment by mhsdesign** [comment]
Hi ;) thank you so much for your pr and the nice write up for context. I love how i get into touch which projects like yours ;)

As running tailwind in the browser is quite a niche usecase - and the pr does not add too much complexity - (though we should check the final bundle size) i think its really sensible to have that. So we only need this one opensource project ^^

Without me actually using it - i just built it for a poc ^^ - it tends to get stale really easy.
So in case you also find that the currently used version is too low feel free to update and test it (last update https://github.com/mhsdesign/jit-browser-tailwindcss/pull/12)

Otherwise i can merge and your pr and tag already with 0.4.2 ;)

**Comment by bkrmendy** [comment]
Thanks for the comments, merging the PR and the tag (I assume a new release is created with each new tag)

**Comment by mhsdesign** [comment]
Tagged as 0.4.2 ;) https://github.com/mhsdesign/jit-browser-tailwindcss/releases/tag/0.4.2
